In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [3]:
np.array([1,2,3,34,23,22,12,21,34]) #1D dimensional array

array([ 1,  2,  3, 34, 23, 22, 12, 21, 34])

In [4]:
a=np.array([1,2,3,34,23,22,12,21,34])
print(a)

[ 1  2  3 34 23 22 12 21 34]


In [5]:
type(a)

numpy.ndarray

In [6]:
new=np.array([[1,2,3],[4,5,6]])
print(new) #2d array

[[1 2 3]
 [4 5 6]]


In [7]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])#3d array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# dtype

In [8]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [9]:
np.array([11,22,33],dtype=bool)

array([ True,  True,  True])

In [10]:
np.array([11,22,33],dtype=complex)

array([11.+0.j, 22.+0.j, 33.+0.j])

# arange

In [11]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# Reshape

In [14]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# ones & Zeros

In [18]:
# np.ones and
np.zeros
np.ones((3, 4 )) # we have to mention iside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.random.random((5,5))

array([[0.15641227, 0.81589767, 0.0750977 , 0.39327674, 0.43536084],
       [0.59356955, 0.52415497, 0.67451174, 0.75675829, 0.06099644],
       [0.75924786, 0.33992847, 0.05193156, 0.35003735, 0.57681856],
       [0.56875133, 0.11276343, 0.61188718, 0.26609852, 0.76747422],
       [0.9830213 , 0.44934098, 0.15988773, 0.60355705, 0.18415415]])

In [21]:
np.arange(-30,10)

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9])

In [22]:
np.arange(3.0) 

array([0., 1., 2.])

In [23]:
np.arange(9.0) 

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [24]:
np.arange(-10,20) 

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])

In [25]:
b=np.arange(-10,20)
b

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])

In [26]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [27]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [28]:
np.arange(10,30,5,1)

TypeError: Cannot interpret '1' as a data type

In [ ]:
np.zeros(2)

In [ ]:
b1=np.zeros(3)
b1

In [ ]:
b1=np.zeros(3,dtype=int)

In [ ]:
b1

In [ ]:
zero = np.zeros((2,2))
zero

In [ ]:
np.zeros((3,3))

In [ ]:
np.zeros((10,10))

In [ ]:
np.zeros((2,10))

In [ ]:
np.zeros((2,2))

In [ ]:
np.zeros((10,30))

In [ ]:
n = (5,7)
n1 = (6,8)
print(np.zeros(n)) # parameter tunnin g
#print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning

In [ ]:
print(np.zeros(n1))

In [ ]:
np.ones(4,dtype=int)

In [ ]:
np.ones((4,4),dtype=int)

In [ ]:
n

In [ ]:
print(np.ones(n,dtype=int))

In [ ]:
np.ones(n,dtype=int)

In [ ]:
np.twos((2,3))

In [ ]:
np.ones((6,10),dtype = int)

In [ ]:
np.twos((2,4))

In [ ]:
np.three((2,4))

In [ ]:
mp.arrange(3)

In [ ]:
from numpy import *
np.arange(3)

In [ ]:
zeros(5)

In [ ]:
range(12)

In [ ]:
list(range(12))

In [ ]:
z=list(range(0,11))
z

In [ ]:
rand(3,2)
random.rand(3,2)

In [ ]:
np.random.rand(4)

In [ ]:
np.rand(4)

In [ ]:
np.random.rand(2,2)

In [ ]:
np.random.randint(3,6)

In [ ]:
np.random.randint(0,2)

In [ ]:
np.random.randint(1,10,4)

In [ ]:
np.random.randint(1,3,5)

In [ ]:
np.random.randint(1,3,5)

In [ ]:
np.random.randint(1,3,5)

In [ ]:
np.random.randint(1) 

In [ ]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

In [ ]:
np.random.randint(10,21,3)

In [ ]:
np.random.randint(1,12,10)

In [ ]:
np.random.randint(10,40,(10,10))

In [ ]:
b=np.random.randint(10,20,(5,4))
b

In [ ]:
b[:]

In [ ]:
b[0:2]

In [ ]:
b

In [ ]:
b[0:-1]

In [ ]:
b

In [ ]:
b[0,2]

In [ ]:
np.random.randint(10,20,(4,4))

# Operations

In [29]:
a = np.random.randint(10,20,5)
a

array([13, 18, 17, 18, 19])

In [ ]:
arr

In [31]:
arr2=np.random.randint(1,100,(10,10))

In [32]:
arr2

array([[16, 93, 65, 21, 28, 84, 11, 19, 33, 83],
       [80, 38, 80, 56, 70, 90, 11, 91, 57, 10],
       [80, 69, 56,  7, 94, 14, 11, 59, 33, 10],
       [37, 12, 82, 73, 67, 28,  7, 11, 98, 56],
       [74, 62, 84, 70, 39, 26, 41,  1, 16, 65],
       [98,  6,  5, 63, 93, 86, 21, 27, 31, 21],
       [18, 20, 93, 14,  6, 20, 17, 75, 15, 14],
       [47, 91, 95, 84, 19,  6, 66, 17, 82, 65],
       [32, 84, 32, 82, 78, 62, 76, 46, 69, 67],
       [59, 75, 41, 93, 72, 36, 92, 73,  7, 47]])

In [34]:
a

array([13, 18, 17, 18, 19])

In [35]:
a[:]

array([13, 18, 17, 18, 19])

In [36]:
a[:4]

array([13, 18, 17, 18])

In [37]:
arr2[:]

array([[16, 93, 65, 21, 28, 84, 11, 19, 33, 83],
       [80, 38, 80, 56, 70, 90, 11, 91, 57, 10],
       [80, 69, 56,  7, 94, 14, 11, 59, 33, 10],
       [37, 12, 82, 73, 67, 28,  7, 11, 98, 56],
       [74, 62, 84, 70, 39, 26, 41,  1, 16, 65],
       [98,  6,  5, 63, 93, 86, 21, 27, 31, 21],
       [18, 20, 93, 14,  6, 20, 17, 75, 15, 14],
       [47, 91, 95, 84, 19,  6, 66, 17, 82, 65],
       [32, 84, 32, 82, 78, 62, 76, 46, 69, 67],
       [59, 75, 41, 93, 72, 36, 92, 73,  7, 47]])

In [38]:
arr2[0:5]

array([[16, 93, 65, 21, 28, 84, 11, 19, 33, 83],
       [80, 38, 80, 56, 70, 90, 11, 91, 57, 10],
       [80, 69, 56,  7, 94, 14, 11, 59, 33, 10],
       [37, 12, 82, 73, 67, 28,  7, 11, 98, 56],
       [74, 62, 84, 70, 39, 26, 41,  1, 16, 65]])

In [40]:
arr2[1,5]

90

In [41]:
arr2[-5,5]

86

In [42]:
arr2[-5,-5]

86

In [43]:
arr2[-1,-2]

7

In [44]:
arr2[::-1]

array([[59, 75, 41, 93, 72, 36, 92, 73,  7, 47],
       [32, 84, 32, 82, 78, 62, 76, 46, 69, 67],
       [47, 91, 95, 84, 19,  6, 66, 17, 82, 65],
       [18, 20, 93, 14,  6, 20, 17, 75, 15, 14],
       [98,  6,  5, 63, 93, 86, 21, 27, 31, 21],
       [74, 62, 84, 70, 39, 26, 41,  1, 16, 65],
       [37, 12, 82, 73, 67, 28,  7, 11, 98, 56],
       [80, 69, 56,  7, 94, 14, 11, 59, 33, 10],
       [80, 38, 80, 56, 70, 90, 11, 91, 57, 10],
       [16, 93, 65, 21, 28, 84, 11, 19, 33, 83]])

In [45]:
arr2[::-2]

array([[59, 75, 41, 93, 72, 36, 92, 73,  7, 47],
       [47, 91, 95, 84, 19,  6, 66, 17, 82, 65],
       [98,  6,  5, 63, 93, 86, 21, 27, 31, 21],
       [37, 12, 82, 73, 67, 28,  7, 11, 98, 56],
       [80, 38, 80, 56, 70, 90, 11, 91, 57, 10]])

In [46]:
arr2[::-3]

array([[59, 75, 41, 93, 72, 36, 92, 73,  7, 47],
       [18, 20, 93, 14,  6, 20, 17, 75, 15, 14],
       [37, 12, 82, 73, 67, 28,  7, 11, 98, 56],
       [16, 93, 65, 21, 28, 84, 11, 19, 33, 83]])

In [48]:
a.max() 

19

In [49]:
a.min()

13

In [50]:
a.mean()

17.0

In [51]:
arr.median()

NameError: name 'arr' is not defined

In [52]:
from numpy import *
a=array([10,20,30,40,50])
median(a)

30.0

In [55]:
a.reshape(2,6)

ValueError: cannot reshape array of size 5 into shape (2,6)

In [59]:
arr=np.random.randint(1,10,6)
arr

array([7, 4, 7, 8, 4, 8])

In [62]:
arr.reshape(3,2)

array([[7, 4],
       [7, 8],
       [4, 8]])

In [64]:
arr.reshape(6,1)

array([[7],
       [4],
       [7],
       [8],
       [4],
       [8]])

In [65]:
arr.reshape(1,6)

array([[7, 4, 7, 8, 4, 8]])

In [66]:
arr.reshape(3,2,order='c')

array([[7, 4],
       [7, 8],
       [4, 8]])

In [67]:
arr.reshape(3,2,order='F') 

array([[7, 8],
       [4, 4],
       [7, 8]])

In [68]:
arr.reshape(3,2,order='A')

array([[7, 4],
       [7, 8],
       [4, 8]])

In [69]:
arr.reshape(3,2,order='K')

ValueError: order 'K' is not permitted for reshaping

In [70]:
arr.reshape(2,3)

array([[7, 4, 7],
       [8, 4, 8]])

In [71]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [72]:
arr.reshape(1,6)  

array([[7, 4, 7, 8, 4, 8]])

In [73]:
arr.reshape(6,1)  

array([[7],
       [4],
       [7],
       [8],
       [4],
       [8]])

In [74]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [75]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

# Indexing

In [76]:
mat = np.arange(0,100)

In [77]:
mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

mat,reshape((10,10))

In [78]:
mat.reshape((10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
mat = np.arange(0,100).reshape(10,10) 

In [80]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

row = 4
col = 5

In [82]:
row = 4 
col = 5

In [83]:
row

4

In [84]:
col

5

In [85]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
mat[row,col]

45

In [89]:
mat[4,5]

45

In [90]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
col=6

In [92]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [94]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [97]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [98]:
mat[:row] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [99]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [100]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [101]:
mat[col:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [102]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [103]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [104]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [105]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [106]:
mat[1,4]

14

In [107]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [108]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [109]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
mat[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [111]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [112]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [113]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [114]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [115]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [118]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [119]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [122]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [121]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [123]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [124]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [125]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [126]:
mat[0,1]

1

In [127]:
mat[1,6]

16

In [128]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [129]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [130]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [131]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [132]:
mat[1:2,2:4]

array([[12, 13]])

In [133]:
mat[2:3,2:3]

array([[22]])

In [134]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [135]:
mat[2:3,4:5]

array([[24]])

# Masking

In [136]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [137]:
id(mat)

2470039094448

In [138]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [140]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [141]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [142]:
mat[mat==50]

array([50])

In [143]:
a1=mat[mat<50]

In [144]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [145]:
a2=mat[mat>50]

In [146]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [148]:
a2=mat[mat>=50]
a2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [149]:
a4 = mat[mat==50]
a4

array([50])

In [150]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [151]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [152]:
a2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])